import { ArrowLeft, ArrowUpRight, BarChart3, Bot, Code2, Database, FileText, LockKeyhole, Rocket, ScanSearch, Sparkles } from 'lucide-react';

const CONTENT = {
  product: { eyebrow: 'Product overview', title: 'One workspace for the decisions behind the model.', intro: 'Axio brings profiling, modeling, explanation, and delivery into one calm surface so teams can move from a file to a confident next step.', icon: Sparkles, cards: [['Profile the data', 'Understand shape, quality, target candidates, and missing values before the first experiment.', ScanSearch], ['Work with an agent', 'Ask questions in plain language and let the assistant turn intent into validated ML actions.', Bot], ['Deliver the result', 'Keep metrics, runs, exports, and context together so the work is easy to share.', Rocket]] },
  workflow: { eyebrow: 'How it works', title: 'A visible path from raw data to a useful model.', intro: 'Every step has a clear purpose. Axio keeps the reasoning close to the result, so you always know what happened and why.', icon: Database, cards: [['01 · Ingest', 'Upload CSV or Excel files and get an instant profile of columns, gaps, and likely targets.', Database], ['02 · Automate', 'Compare practical model paths, train with a held-out split, and optionally validate with cross-validation.', Bot], ['03 · Explain', 'Inspect metrics, feature importance, charts, and the conversation behind each choice.', BarChart3], ['04 · Ship', 'Download the trained artifact and carry the result into your next system.', Code2]] },
  features: { eyebrow: 'Capabilities', title: 'The essential tools, without the control-panel feeling.', intro: 'Axio is intentionally focused: fewer tabs, clear feedback, and enough depth for serious experimentation.', icon: BarChart3, cards: [['Instant profiling', 'See data types, missingness, unique values, and recommended targets in seconds.', ScanSearch], ['Agentic AutoML', 'Ask for a model, charts, or feature statistics and get an answer grounded in your dataset.', Bot], ['Explainable metrics', 'Understand performance and the signals that shaped the prediction.', BarChart3], ['Export-ready', 'Download a reusable model artifact when the work is ready to leave the workspace.', Code2]] },
  resources: { eyebrow: 'Resources', title: 'A practical starting point for better ML decisions.', intro: 'Use these guides to get value from Axio quickly, whether you are exploring a dataset or preparing a model for delivery.', icon: FileText, cards: [['Quickstart guide', 'Upload a dataset, review the profile, and ask the agent to recommend a first modeling path.', FileText], ['Modeling checklist', 'Check target quality, missing values, leakage risks, and validation before trusting a metric.', ScanSearch], ['Workspace security', 'Projects are isolated by authenticated user ownership, with JWT-protected API access.', LockKeyhole]] },
  privacy: { eyebrow: 'Legal', title: 'Privacy', intro: 'Your workspace is designed around authenticated access and project ownership. Configure deployment storage, retention, and provider settings to match your organization’s requirements.', icon: LockKeyhole, cards: [['Access control', 'Protected APIs use bearer tokens and project records are scoped to the signed-in user.', LockKeyhole], ['Your data flow', 'Uploaded files are processed by the Axio backend and remain available for the workspace workflow.', Database]] },
  terms: { eyebrow: 'Legal', title: 'Terms of use', intro: 'Axio is a decision-support workspace. Review outputs, validate models on your own data, and keep a human accountable for consequential decisions.', icon: FileText, cards: [['Use responsibly', 'Do not treat automated metrics or recommendations as a substitute for domain review.', Sparkles], ['Know your deployment', 'Configure secrets, storage, and access policies before exposing a production instance.', LockKeyhole]] },
  docs: { eyebrow: 'Documentation', title: 'Build with Axio', intro: 'The API supports authenticated users, project management, dataset uploads, training, prediction, chat, and model export.', icon: Code2, cards: [['Authentication', 'Register or sign in, then send Authorization: Bearer <token> on protected requests.', LockKeyhole], ['Core endpoints', 'Use /api/projects, /upload, /train, /predict, /chat, and /export/model/{session_id}.', Code2]] },
};

export default function LandingDetail({ page, onBack, onNavigate }) {
  const content = CONTENT[page] || CONTENT.product;
  const PageIcon = content.icon;
  return <main className="landing-detail page-transition">
    <nav className="landing-detail-nav"><button className="detail-back" onClick={onBack}><ArrowLeft size={16} /> Back to Axio</button><div className="detail-brand"><span className="brand-mark">A</span> axio <small>ML OS</small></div><button className="detail-workspace" onClick={() => onNavigate('workspace')}>Open workspace <ArrowUpRight size={15} /></button></nav>
    <section className="detail-hero"><div className="detail-copy"><span className="eyebrow">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p></div><div className="detail-icon-orbit"><PageIcon size={34} /><span>AXIO</span></div></section>
    <section className="detail-grid">{content.cards.map(([title, body, Icon], index) => { const CardIcon = Icon; return <article className="detail-card" key={title} style={{ '--delay': `${index * 80}ms` }}><div className="detail-card-icon"><CardIcon size={20} /></div><span>0{index + 1}</span><h2>{title}</h2><p>{body}</p></article>; })}</section>
    <div className="detail-footer"><span>Ready to see it in action?</span><button className="axio-button lime" onClick={() => onNavigate('workspace')}>Start building <ArrowUpRight size={16} /></button></div>
  </main>;
}
